# Basic site setup
remote_theme: JakeSteam/minimaJake
title: Osaka Ripped Flyers
description: Gigs and shit in Osaka <br>大阪のライブとかクソみたいなやつ
accent_colour: "#ff0000"
# url: https://history.jakelee.co.uk
future: true

#baseurl:
url: https://osaka.rippedflyers.net/


#langauge settings for language toggle
lang: en
lang_toggle: 
  enabled: true
  languages:
    - { code: 'en', name: 'English'}
    - { code: 'ja', name: '日本語'}

collections:
  posts:
    output: true
    permalink: /p/:title
  authors:
    output: true
    permalink: /a/:title

month_display: 2
month_columns: 2

# Setting article defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"

footer_links:
  - { user_title: 'About', user_url: '/about/'}
  - { user_title: 'GitHub', user_url: "https://github.com/rippedflyers/osaka"}
  - { user_title: "RSS Feed", user_title_ja: "RSSフィード", user_url: "/feed.xml" }

# Social / dark mode settings
minima:
  skin: auto
  social_links:
    - { platform: github, user_url: "https://github.com/vriibot" }
    - {
        platform: code,
        user_url: "https://github.com/vriibot/insta-calendar",
        user_title: "vriibot/insta-calendar",
      }
    - { platform: rss, user_url: "/feed.xml", user_title: "RSS Feed" }

###
# Below here probably doesn't need changing #
###

# Site settings
permalink: /:title/
show_excerpts: true
timezone: UTC

# Build settings
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-webp

# Pagination settings
# paginate: 10
# paginate_path: page/:num/