name: mine

on: workflow_dispatch

permissions:
  contents: write
  pull-requests: write

jobs:
  run_scripts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Do session
        uses: mobiledevops/secret-to-file-action@v1
        with:
          base64-encoded-secret: ${{ secrets.SESSION }}
          filename: "session.json"
          is-executable: false
          working-directory: "data"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Python script mine
        run: python main.py
        env:
          INSTAGRAM_USERNAME: ${{ secrets.USERNAME }}
          INSTAGRAM_PASSWORD: ${{ secrets.PASSWORD }}
          PROXY_USERNAME: ${{ secrets.PROXY_USERNAME }}
          PROXY_PASSWORD: ${{ secrets.PROXY_PASSWORD }}
          PROXY_COUNTRY: ${{ secrets.PROXY_COUNTRY }}
          PROXY_HOST_PORT: ${{ secrets.PROXY_HOST_PORT }}

      - name: Check if posts.csv changed
        id: check_posts
        run: |
          git add -A
          if git diff --cached --quiet -- "data/posts.csv"; then
            echo "posts_changed=false" >> $GITHUB_OUTPUT
          else
            echo "posts_changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Check if users.csv changed
        id: check_users
        run: |
          git add -A
          if git diff --cached --quiet -- "data/users.csv"; then
            echo "users_changed=false" >> $GITHUB_OUTPUT
          else
            echo "users_changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Run post-maker script
        if: steps.check_posts.outputs.posts_changed == 'true'
        run: python post-maker.py

      - name: Run author-maker script
        if: steps.check_users.outputs.users_changed == 'true'
        run: python author-maker.py

      - name: Create PR
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: Update Posts
          branch: action/update-posts
          title: "Update Posts"
          body: |
            This PR includes auto-generated files from the GitHub Action run.
          
